#!/usr/bin/python

import argparse

from data_analyzer import DataAnalyzer
from graph import Graph
from histogram import *


def main():
    # Argument parser
    parser = argparse.ArgumentParser(description="Issuu CW2 data analyzer")
    parser.add_argument("-f", "--file", help="The file path with json data")
    parser.add_argument("-u", "--uuid", help="User uuid to select")
    parser.add_argument("-d", "--document", help="The document UUID to select")
    parser.add_argument("-t", "--task", help="The task of the coursework [2a, 2b, 3a, 3b, 4d, 5, 6]", required=True)
    args = parser.parse_args()

    task = args.task

    # This object handle the data from Pandas
    p = None
    if args.file is not None:
        p = DataAnalyzer(args.file)

    if task == "2a":
        if args.document is None:
            print("Missing uuid argument")
            exit(1)
        if args.file is None:
            print("Missing file argument")
            exit(1)

        # Show the graph of countries using matplotlib
        showCountries(p.getCountries(args.document))

    elif task == "2b":
        if args.document is None:
            print("Missing uuid argument")
            exit(1)
        if args.file is None:
            print("Missing file argument")
            exit(1)
        # Show the graph of continents using matplotlib
        showContinent(p.getContinents(args.document))

    elif task == "3a":
        # Show the graph of all the users agents
        if args.file is None:
            print("Missing file argument")
            exit(1)
        showUserAgents(p.getUserAgents())

    elif task == "3b":
        # Show the graph of views per browser
        if args.file is None:
            print("Missing file argument")
            exit(1)
        showBrowsers(p.getBrowsers())

    elif task == "4d":
        if args.document is None:
            print("Missing document argument")
            exit(1)
        if args.file is None:
            print("Missing file argument")
            exit(1)
        # Getting the top 10 files that this user may likes
        # The uuid remove the user from the list
        list = p.topTenDocumentsSeen(args.document, args.uuid)

        # Check if documents has been found
        if list is None or len(list) == 0:
            print("No documents has been found")
        else:
            print("Here the top 10 documents this user may like")
            for i in range(len(list)):
                print("{0}: {1}".format(i + 1, list[i]))

    elif task == "5":
        # Creation of a graphviz Graph by calling our object Graph

        if args.document is None:
            print("Missing document argument")
            exit(1)
        if args.file is None:
            print("Missing file argument")
            exit(1)

        if args.uuid is None:
            Graph(p, uuid=None, document=args.document)
        else:
            Graph(p, uuid=args.uuid, document=args.document)

    elif task == "6":
        print("Not implemented yet")

    else:
        print("Error: Task not in range [2a, 2b, 3a, 3b, 4d, 5, 6]")


main()
